name: Update Card Description

on:
  project_card:
    types: [created, moved]

jobs:
  update_description:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Update card description
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TARGET_COLUMN_NAME: "今日やった"  # 特定のカラム名をここに記載
      run: |
        # Get the column ID where the card was moved
        COLUMN_ID=${{ github.event.project_card.column_id }}

        # Get the project card ID
        CARD_ID=${{ github.event.project_card.id }}

        # Fetch the column details using GitHub API
        COLUMN_DETAILS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.inertia-preview+json" \
          https://api.github.com/projects/columns/$COLUMN_ID)

        # Extract the column name
        COLUMN_NAME=$(echo "$COLUMN_DETAILS" | jq -r .name)

        # Check if the card is in the target column
        if [ "$COLUMN_NAME" == "$TARGET_COLUMN_NAME" ]; then
          # Get the current date
          DATE=$(date +'%Y-%m-%d')

          # Update the project card description
          DESCRIPTION="Description updated on $DATE"
          curl -X PATCH \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.inertia-preview+json" \
            https://api.github.com/projects/columns/cards/$CARD_ID \
            -d '{"note":"'"$DESCRIPTION"'"}'
        fi
